name: agentscan-production
region: nyc1

services:
  - name: api
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: nikhilsetiya/agentscan-security-scanner
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    envs:
      - key: PORT
        value: "8080"
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: REDIS_HOST
        value: ${redis.HOSTNAME}
      - key: REDIS_PORT
        value: ${redis.PORT}
      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
      - key: GITHUB_CLIENT_ID
        value: ${GITHUB_CLIENT_ID}
        type: SECRET
      - key: GITHUB_SECRET
        value: ${GITHUB_SECRET}
        type: SECRET
      - key: ENVIRONMENT
        value: production

databases:
  - name: db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1
    production: true

  - name: redis
    engine: REDIS
    version: "7"
    size: basic-xs
    num_nodes: 1
    production: true