apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentscan-orchestrator
  namespace: agentscan
  labels:
    app: agentscan-orchestrator
    component: orchestrator
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: agentscan-orchestrator
      version: v1
  template:
    metadata:
      labels:
        app: agentscan-orchestrator
        component: orchestrator
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: agentscan-orchestrator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: orchestrator
        image: agentscan/orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8082
          name: metrics
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: ORCHESTRATOR_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: agentscan-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agentscan-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agentscan-secrets
              key: REDIS_PASSWORD
        - name: MAX_CONCURRENT_SCANS
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: MAX_CONCURRENT_SCANS
        - name: SCAN_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: agentscan-config
              key: SCAN_TIMEOUT
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: agent-cache
          mountPath: /app/agent-cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: agent-cache
        emptyDir:
          sizeLimit: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - agentscan-orchestrator
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: agentscan-orchestrator
  namespace: agentscan
  labels:
    app: agentscan-orchestrator
    component: orchestrator
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 8082
    targetPort: 8082
    name: metrics
  selector:
    app: agentscan-orchestrator
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentscan-orchestrator
  namespace: agentscan
  labels:
    app: agentscan-orchestrator
    component: orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentscan-orchestrator
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agentscan-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agentscan-orchestrator
subjects:
- kind: ServiceAccount
  name: agentscan-orchestrator
  namespace: agentscan